# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoType',
            fields=[
                ('info_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_key', models.TextField(verbose_name=b'census key')),
                ('description', models.TextField(verbose_name=b'Data description')),
            ],
        ),
        migrations.CreateModel(
            name='CensusInfo',
            fields=[
                ('census_info_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type_id', models.IntegerField(verbose_name=b'Foreign key for what type of info is stored')),
                ('info', models.IntegerField(verbose_name=b'Data for the zip code')),
                ('zipCode', models.TextField(verbose_name=b'zipcode data is for')),
                ('state_code', models.IntegerField(verbose_name=b'Numerical state code used by the census api')),
            ],
        ),
    ]
